# Generated by Django 5.0 on 2023-12-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productbrand_products_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='', max_length=300, null=True, unique=True),
        ),
    ]
