# Generated by Django 5.0 on 2023-12-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', max_length=300, unique=True),
        ),
    ]
