# Generated by Django 5.0 on 2023-12-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم')),
                ('site_url', models.CharField(max_length=200, verbose_name='url سایت')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('phone', models.CharField(max_length=200, verbose_name='شماره تماس')),
                ('fax', models.CharField(max_length=200, verbose_name='فکس')),
                ('email', models.CharField(max_length=200, verbose_name='ایمیل')),
                ('copy_right', models.TextField(verbose_name='متن کپی رایت')),
                ('about_us', models.TextField(verbose_name='درباره سایت')),
                ('site_logo', models.ImageField(upload_to='images/sitelogo', verbose_name='لوگو سایت')),
                ('is_main_settings', models.BooleanField(verbose_name='تنظیمات اصلی')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
