# Generated by Django 5.0 on 2023-12-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_footerlinktitle_slider_footerlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
