# Generated by Django 5.0 on 2023-12-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_module', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact_us',
            new_name='ContactUs',
        ),
    ]
