# Generated by Django 5.0 on 2023-12-19 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_module', '0002_rename_contact_us_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='kfdjsa',
            field=models.TextField(null=True),
        ),
    ]
