# Generated by Django 5.0 on 2023-12-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_module', '0003_contactus_kfdjsa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=500, verbose_name='ایمیل')),
                ('message', models.TextField(verbose_name='توضیحات')),
                ('is_read', models.BooleanField(verbose_name='خوانده شده')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('response', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
            ],
            options={
                'verbose_name': 'تماس با ما',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
