# Generated by Django 5.0 on 2023-12-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us_module', '0004_contact_us_delete_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
