# Generated by Django 5.0 on 2023-12-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('image', models.ImageField(upload_to='images/slider', verbose_name='')),
                ('url', models.URLField(max_length=500, verbose_name='')),
                ('url_name', models.CharField(max_length=200, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
    ]
